apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ewv2imeh2-go
  janus-idp.io/tekton: ewv2imeh2-go
  backstage.io/kubernetes-id: ewv2imeh2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ewv2imeh2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
